# Generated by Django 5.0.6 on 2024-06-13 02:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIYNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='diynews/covers/')),
                ('html_content', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
