# Generated by Django 5.0.6 on 2024-07-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diynews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
                ('title', models.CharField(max_length=150)),
                ('action_name', models.CharField(max_length=50)),
                ('link', models.TextField(blank=True, null=True)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
    ]
