# Generated by Django 5.0.6 on 2024-07-03 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
