# Generated by Django 5.0.6 on 2024-07-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_img_slide_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DIYNews',
        ),
    ]
