# Generated by Django 5.0.6 on 2024-07-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_numbers', models.TextField(help_text='Separate multiple numbers with commas')),
                ('service_emails', models.TextField(help_text='Separate multiple emails with commas')),
                ('youtube_urls', models.TextField(help_text='Separate multiple URLs with commas')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('about_us', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Business Information',
            },
        ),
    ]
