# Generated by Django 5.0.6 on 2024-07-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businessinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessinfo',
            old_name='twitter_url',
            new_name='youtube_url',
        ),
    ]
