# Generated by Django 5.0.6 on 2024-07-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_twitter_url_businessinfo_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='phone_numbers',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='service_emails',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='youtube_urls',
        ),
    ]
