# Generated by Django 5.0.6 on 2024-07-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_company_name_businessinfo_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='business/')),
                ('body', models.TextField()),
                ('business_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.businessinfo')),
            ],
        ),
    ]
