# Generated by Django 5.0.6 on 2024-07-10 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_businesspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspost',
            name='business_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='core.businessinfo'),
        ),
    ]
