# Generated by Django 5.0.6 on 2024-07-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_businesspost_business_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspost',
            name='home_page_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businesspost',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
