# Generated by Django 5.0.6 on 2024-08-01 06:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_businesspost_home_page_body_alter_businesspost_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
