# Generated by Django 5.0.6 on 2024-06-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_trigram_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('CI', 'Classic with Image'), ('CN', 'Classic without Image'), ('VI', 'Video'), ('CA', 'Carousel')], default='CI', max_length=2),
        ),
    ]
