# Generated by Django 5.0.6 on 2024-06-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_post_type_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carousel_image1',
            field=models.ImageField(blank=True, null=True, upload_to='posts/carousel_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='carousel_image2',
            field=models.ImageField(blank=True, null=True, upload_to='posts/carousel_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='carousel_image3',
            field=models.ImageField(blank=True, null=True, upload_to='posts/carousel_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='classic_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/classic_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
