# Generated by Django 5.0.6 on 2024-06-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_carousel_image1_post_carousel_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
