# Generated by Django 5.0.6 on 2024-06-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_collection_product_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collections',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
