# Generated by Django 5.0.6 on 2024-06-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_collection_product_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='handle',
            field=models.CharField(default='default-handle', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='handle',
            field=models.CharField(default='k', max_length=200),
            preserve_default=False,
        ),
    ]
