# Generated by Django 5.0.6 on 2024-07-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_handle_productimage_handle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
