# Generated by Django 5.0.6 on 2024-07-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order', 'name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
